[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/data/**", "netlify/functions/templates/**"]

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
